**Zadanie 1**

In [ ]:
import pandas as pd

In [ ]:
dane = pd.read_csv('Polonia Bytom_Pogo  Grodzisk Mazowiecki_4068759.csv')

In [ ]:
dane

,id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,...,483440_interception_like_defensive_responsibility_probability,483427_interception_like_defensive_responsibility_probability,494440_interception_like_defensive_responsibility_probability,563697_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
0,b981cdbd-dec2-4760-a876-d9a270d55ec7,1,4068759,1,00:00,0,0,35,Starting XI,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,442bed77-90da-436e-ad7c-adebe51a2ef4,2,4068759,1,00:00,0,0,35,Starting XI,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4f95b807-be3e-4454-ae86-f41f2c07bd98,3,4068759,1,00:00:00.000,0,0,18,Half Start,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,98f74581-8d07-59c8-84e5-ec8b9e0a3512,4,4068759,1,00:00:00.000,0,0,18,Half Start,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,c58f5f95-bea5-4810-bf21-9411033e92b9,5,4068759,1,00:00:00.399,0,0,30,Pass,2,...,NaN,0.000035,NaN,NaN,1.0,False,True,-0.078626,0.0,midfield_third
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3887,028c9f3d-a3f1-4873-b065-7ed93c450a9f,2635,4068759,2,00:30:52.390,75,52,36,Tactical Shift,169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3888,028c9f3d-a3f1-4873-b065-7ed93c450a9f,2635,4068759,2,00:30:52.390,75,52,36,Tactical Shift,169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3889,028c9f3d-a3f1-4873-b065-7ed93c450a9f,2635,4068759,2,00:30:52.390,75,52,36,Tactical Shift,169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3890,028c9f3d-a3f1-4873-b065-7ed93c450a9f,2635,4068759,2,00:30:52.390,75,52,36,Tactical Shift,169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3891,028c9f3d-a3f1-4873-b065-7ed93c450a9f,2635,4068759,2,00:30:52.390,75,52,36,Tactical Shift,169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dane['event_type_name'].unique()

array(['Starting XI', 'Half Start', 'Pass', 'Ball Receipt*', 'Carries',
       'Block', 'Pressure', 'Ball Recovery', 'Duel', 'Clearance',
       'Defensive Duel', 'Offensive Duel', 'Foul Committed', 'Foul Won',
       'Miscontrol', 'Shot', 'Goal Keeper', 'Dispossessed', 'Dribble',
       'Dribbled Past', 'Interception', 'Shield', 'Loose Ball Duel',
       'Half End', 'Tactical Shift', 'Injury Stoppage', 'Player Off',
       'Player On', 'Substitution', '50/50', 'Bad Behaviour'],
      dtype=object)

In [ ]:
dane['outcome_name'].unique()

array([nan, 'Incomplete', 'Out', 'Off T', 'Blocked', 'Lost In Play',
       'Claim', 'Success In Play', 'Complete', 'Saved', 'Success', 'Won',
       'Lost Out', 'Goal', 'No Touch', 'Pass Offside', 'In Play Safe',
       'Unknown', 'Clear', 'Tactical', 'Lost', 'Success To Team',
       'Success Out', 'Yellow Card', 'Saved Twice'], dtype=object)

In [ ]:
kolumny = dane[['event_type_name','outcome_name','index','statsbomb_xg','team_name']]

In [ ]:
dane = pd.read_csv('Polonia Bytom_Pogo  Grodzisk Mazowiecki_4068759.csv', usecols = kolumny)

In [ ]:
dane.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3892 entries, 0 to 3891
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            3892 non-null   int64
 1   event_type_name  3892 non-null   object
 2   team_name        3892 non-null   object
 3   statsbomb_xg     628 non-null    float64
 4   outcome_name     924 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 152.2+ KB

Dane zostały wczytane oraz ograniczone do potrzebnych kolumn.

Przechodzę do czyszczenia i przygotowania danych.

In [ ]:
dane = dane.drop_duplicates(subset=['index']).copy()
dane

,index,event_type_name,team_name,statsbomb_xg,outcome_name
0,1,Starting XI,Polonia Bytom,NaN,NaN
1,2,Starting XI,Pogoń Grodzisk Mazowiecki,NaN,NaN
2,3,Half Start,Polonia Bytom,NaN,NaN
3,4,Half Start,Pogoń Grodzisk Mazowiecki,NaN,NaN
4,5,Pass,Polonia Bytom,NaN,NaN
...,...,...,...,...,...
3227,3228,Offensive Duel,Pogoń Grodzisk Mazowiecki,NaN,NaN
3228,3229,Foul Committed,Polonia Bytom,NaN,NaN
3229,3230,Foul Won,Pogoń Grodzisk Mazowiecki,NaN,NaN
3230,3231,Half End,Polonia Bytom,NaN,NaN
3231,3232,Half End,Pogoń Grodzisk Mazowiecki,NaN,NaN

Na tym etapie pozbywamy się powtarzających się indexów. Każde zdarzenie posiada swój indywidualny index, więc jego duplikat to powtórzenie tego samego zdarzenia.

In [ ]:
dane

,index,event_type_name,team_name,statsbomb_xg,outcome_name
0,1,Starting XI,Polonia Bytom,NaN,NaN
1,2,Starting XI,Pogoń Grodzisk Mazowiecki,NaN,NaN
2,3,Half Start,Polonia Bytom,NaN,NaN
3,4,Half Start,Pogoń Grodzisk Mazowiecki,NaN,NaN
4,5,Pass,Polonia Bytom,NaN,NaN
...,...,...,...,...,...
3227,3228,Offensive Duel,Pogoń Grodzisk Mazowiecki,NaN,NaN
3228,3229,Foul Committed,Polonia Bytom,NaN,NaN
3229,3230,Foul Won,Pogoń Grodzisk Mazowiecki,NaN,NaN
3230,3231,Half End,Polonia Bytom,NaN,NaN
3231,3232,Half End,Pogoń Grodzisk Mazowiecki,NaN,NaN

In [ ]:
dane = dane.sort_values('index').reset_index(drop=True)
dane

,index,event_type_name,team_name,statsbomb_xg,outcome_name
0,1,Starting XI,Polonia Bytom,NaN,NaN
1,2,Starting XI,Pogoń Grodzisk Mazowiecki,NaN,NaN
2,3,Half Start,Polonia Bytom,NaN,NaN
3,4,Half Start,Pogoń Grodzisk Mazowiecki,NaN,NaN
4,5,Pass,Polonia Bytom,NaN,NaN
...,...,...,...,...,...
3227,3228,Offensive Duel,Pogoń Grodzisk Mazowiecki,NaN,NaN
3228,3229,Foul Committed,Polonia Bytom,NaN,NaN
3229,3230,Foul Won,Pogoń Grodzisk Mazowiecki,NaN,NaN
3230,3231,Half End,Polonia Bytom,NaN,NaN
3231,3232,Half End,Pogoń Grodzisk Mazowiecki,NaN,NaN

Sortuję wydarzenia meczowe chronologicznie.

In [ ]:
dane['statsbomb_xg'] = dane['statsbomb_xg'].fillna(0)
dane

,index,event_type_name,team_name,statsbomb_xg,outcome_name
0,1,Starting XI,Polonia Bytom,0.0,NaN
1,2,Starting XI,Pogoń Grodzisk Mazowiecki,0.0,NaN
2,3,Half Start,Polonia Bytom,0.0,NaN
3,4,Half Start,Pogoń Grodzisk Mazowiecki,0.0,NaN
4,5,Pass,Polonia Bytom,0.0,NaN
...,...,...,...,...,...
3227,3228,Offensive Duel,Pogoń Grodzisk Mazowiecki,0.0,NaN
3228,3229,Foul Committed,Polonia Bytom,0.0,NaN
3229,3230,Foul Won,Pogoń Grodzisk Mazowiecki,0.0,NaN
3230,3231,Half End,Polonia Bytom,0.0,NaN
3231,3232,Half End,Pogoń Grodzisk Mazowiecki,0.0,NaN

In [ ]:
strzaly = dane[dane['event_type_name'] == 'Shot']

In [ ]:
print(strzaly['outcome_name'].value_counts())

outcome_name
Off T      13
Blocked    10
Saved       7
Goal        4
Name: count, dtype: int64

Dane zostały oczyszczone i przygotowane do dalszych obliczeń. Na etapie weryfikacji poprawności danych pozbyłem się 660 wierszy, z powodu duplikatów. Dodatkowo NaN w kolumnie statsbomb_xg zostało zastąpione 0.

In [ ]:
wynik = {'Polonia Bytom': 0, 'Pogoń Grodzisk Mazowiecki': 0}

statystyki_xg = {
    'Polonia Bytom': {
        'Prowadzenie': {'xGF': 0.0, 'xGA': 0.0},
        'Remis': {'xGF': 0.0, 'xGA': 0.0},
        'Przegrana': {'xGF': 0.0, 'xGA': 0.0}
    },
    'Pogoń Grodzisk Mazowiecki': {
        'Prowadzenie': {'xGF': 0.0, 'xGA': 0.0},
        'Remis': {'xGF': 0.0, 'xGA': 0.0},
        'Przegrana': {'xGF': 0.0, 'xGA': 0.0}
    }
}

for _, row in dane.iterrows():

    if wynik['Polonia Bytom'] > wynik['Pogoń Grodzisk Mazowiecki']:
        stan_polonia = 'Prowadzenie'
        stan_pogon = 'Przegrana'
    elif wynik['Polonia Bytom'] < wynik['Pogoń Grodzisk Mazowiecki']:
        stan_polonia = 'Przegrana'
        stan_pogon = 'Prowadzenie'
    else:
        stan_polonia = 'Remis'
        stan_pogon = 'Remis'

    if row['event_type_name'] == 'Shot':
        xg = row['statsbomb_xg']
        druzyna = row['team_name']

        if druzyna == 'Polonia Bytom':
            statystyki_xg['Polonia Bytom'][stan_polonia]['xGF'] += xg
            statystyki_xg['Pogoń Grodzisk Mazowiecki'][stan_pogon]['xGA'] += xg
        elif druzyna == 'Pogoń Grodzisk Mazowiecki':
            statystyki_xg['Pogoń Grodzisk Mazowiecki'][stan_pogon]['xGF'] += xg
            statystyki_xg['Polonia Bytom'][stan_polonia]['xGA'] += xg

    if row['outcome_name'] == 'Goal':
        wynik[row['team_name']] += 1

dane_do_tabeli = []

for druzyna in statystyki_xg:
    for stan in ['Prowadzenie', 'Remis', 'Przegrana']:
        xgf = statystyki_xg[druzyna][stan]['xGF']
        xga = statystyki_xg[druzyna][stan]['xGA']

        dane_do_tabeli.append({
            'Drużyna': druzyna,
            'Stan meczu': stan,
            'xGF': round(xgf, 3),
            'xGA': round(xga, 3),
            'Różnica xG': round(xgf - xga, 3)
        })
tabela_wynikow = pd.DataFrame(dane_do_tabeli)
tabela_wynikow

                     Drużyna   Stan meczu    xGF    xGA  Różnica xG
0              Polonia Bytom  Prowadzenie  0.066  0.017       0.050
1              Polonia Bytom        Remis  0.923  0.609       0.314
2              Polonia Bytom    Przegrana  0.079  0.117      -0.038
3  Pogoń Grodzisk Mazowiecki  Prowadzenie  0.117  0.079       0.038
4  Pogoń Grodzisk Mazowiecki        Remis  0.609  0.923      -0.314
5  Pogoń Grodzisk Mazowiecki    Przegrana  0.017  0.066      -0.050

Powyższy fragment kodu oblicza bilans oczekiwanych goli (xG) w zależności od stanu meczu (Prowadzenie, Remis, Przegrana).

Dynamiczny wynik -  Pętla na bieżąco śledzi wynik, ustalając kontekst na boisku przed każdym zdarzeniem.

Kategoryzacja strzałów - Wartość statsbomb_xg powiększa pulę wykreowanego (xGF) i dopuszczonego (xGA) zagrożenia dla odpowiednich drużyn w bieżącym stanie gry.

Chronologia zdarzeń -  Bramki zmieniają wynik dopiero po zaksięgowaniu strzału. Dzięki temu gol dający prowadzenie poprawnie przypisuje się do statystyk przy "Remisie".

Zestawienie końcowe: Agregowane dane trafiają do tabeli wraz z obliczoną różnicą xG.

In [ ]:
tabela_wynikow.to_csv('wyniki_xg_pogon.csv', index=False, sep=';', decimal=',')

Wyniki wyświetlają się powyżej oraz zostały wyeksportowane do pliku csv do osobnego wglądu.

**Zadanie 2**

Dostajesz pytanie, czy zawodnik X nadaje się na wahadłowego w naszym
systemie. Masz dane StatsBomb z jego 20 meczów. Opisz, jak byś do tego
podszedł i gdzie te dane Cię zawiodą.

Ocena przydatności zawodnika na pozycję wahadłowego wymaga przejścia od założeń taktycznych do konkretnych wskaźników liczbowych. Poniżej przedstawiam metodologię opartą na danych eventowych ze StatsBomb, podzieloną na kluczowe obszary analityczne.

**Etap I**

**Definicja systemu i założeń taktycznych**

Praca z surowym zbiorem zdarzeń musi być poprzedzona jasnym określeniem potrzeb sztabu szkoleniowego Pogoni. Zamiast zakładać uniwersalny, z góry narzucony profil wahadłowego, najpierw definiuję pożądany model gry – ustalając, czy zespół wymaga klasycznego gracza zapewniającego szerokość, czy odwróconego wahadła operującego w półprzestrzeniach. Wyselekcjonowanie odpowiednich cech i kluczowych wskaźników z bazy danych jest bezpośrednią odpowiedzią na tę definicję.

**Etap II**

Zakładając, że już znam profil zawodnika, jakiego poszukujemy, przechodzę do działania na danych. W zależności od profilu zawodnika mogę podzielić ten punkt na 3 mniejsze.

**1. Gra z piłką**

Progresja i zdobywanie przestrzeni - weryfikuję podania (Pass) oraz rajdy z piłką (Carry), koncentrując się na zagraniach progresywnych. Oceniam nie tylko surową celność, ale faktyczny wkład zawodnika w płynne transportowanie ciężaru gry do wyższych sektorów i przełamywanie linii pressingu rywala.

Jakość w ofensywie - Analizuję zachowania w pojedynkach 1 na 1, filtrując zdarzenia typu Dribble w połączeniu z ich ostatecznym rezultatem. Pozwala to sprawdzić, czy wahadłowy potrafi przełamać strukturę obronną rywala na skrzydle i samodzielnie wykreować przewagę.

Kluczowe zagrania w ostatniej tercji - Zamiast liczyć same dośrodkowania, weryfikuję ich realną wartość. Mapuję zagrania docierające w pole karne i zestawiam je z modelem statsbomb_xg strzałów oddanych bezpośrednio po nich (kluczowe podania/Expected Assists). Dzięki temu jestem w stanie obiektywnie ocenić, czy dane zagranie przyniosło realną korzyść.

**2. Gra w defensywie**

Zachowanie w fazie przejścia - Wykorzystuję wskaźniki takie jak counterpress, by zbadać reakcję zawodnika bezpośrednio po stracie piłki. Weryfikuje to, czy jego nawyki taktyczne odpowiadają systemom, które w bocznych sektorach wymagają agresywnego, natychmiastowego doskoku.

Jakość w pojedynkach - Zamiast opierać się wyłącznie na surowym procencie wygranych starć (Duel), zestawiam je z metryką duel_win_probability. Pozwala to zidentyfikować, czy gracz potrafi regularnie wygrywać trudne piłki, oferując zespołowi realną nadwyżkę w grze obronnej.

Geometria działań obronnych - Mapuję współrzędne przestrzenne interwencji, takich jak przecięcia podań i bloki. Heatmapa defensywna precyzyjnie wskaże, czy zawodnik odważnie skraca pole gry i czyta intencje rywala wyżej, czy ma tendencję do pasywnej, zbyt głębokiej asekuracji.

**3. Poruszanie się po boisku - profil przestrzenny**

Zasięg i strefy aktywności - na podstawie współrzędnych zawartych w danych tworzę heatmapy ze wszystkich kontaktów z piłką. Pozwoli to na ocenę zakresu poruszania się zawodnika - czy jest przyklejony do linii bocznej, czy ma tendencje do schodzenia do środka.
Badam również wertykalność zagrań - analiza kierunków rajdów oraz podań - pozwoli to na ocenę, czy zawodnik odważnie wprowadza piłkę do strefy ataku, czy gra zachowawczo.

**Etap III**

Na tym etapie badam kontekst ligowy. Same wyliczone wartości nic nam nie mówią, dopóki nie mamy porównania do pozostałych. W tym celu sprawdzam, jak zawodnik X spisywał się na tle ligi w postaci percentyli. Pozwala to zweryfikować, jak bardzo zawodnik wyróżnia się w kluczowych aspektach na tle ligi. Takie porównanie pozwala też na zwizualizowanie, np. w postaci wykresu radarowego mocnych i słabych stron gracza na tle ligi. Opcjonalnie, w przypadku dostępu do szerszej bazy, przepuszczam profil zawodnika przez modele uczenia maszynowego, grupujące wahadłowych na podstawie ich zachowań boiskowych. Pozwoli to na szybką odpowiedź na pytanie, czy zawodnik X ma profil zbliżony do sprawdzonych w systemie Pogoni zawodników.

**Etap IV**

Przygotowanie raportu oraz problem z danymi.
Wyniki analizy wraz z wykresami oraz wizualizacjami kompresuję w raport analityczny, który dostarczy czytelną pigułkę decyzyjną sztabowi szkoleniowemu, eliminując potrzebę przebijania się przez surowe liczby.
Wyraźnie zaznaczam to, czego dane eventowe ze StatsBomb nie widzą. Nie zawierają one informacji o pracy bez piłki oraz kwestii fizycznych - intensywności obiegów, sprintów czy wytrzymałości zawodnika, co w przypadku wahadłowego jest bardzo istotne. W tym celu będzie konieczna analiza wizualna gry zawodnika, która pozwoli na ocenę tych cech.
Na tym etapie warto również wspomnieć, że dane z ostatnich meczów zawodnika opierają się na grze innej drużyny, często o innym profilu taktycznym lub sposobie grania. Stąd czyste dane liczbowe niekoniecznie będą dobrze odzwierciedlały profil zawodnika w 100 procentach. Mógł on być ograniczany przez sposób grania drużyny. To również trzeba brać pod uwagę w końcowym raporcie.